### ISSUE TITLE
Warning: assigning incompatible type

### ISSUE THREAD

**Issue by Emailrus** [bfeher/BFPaperTableViewCell#16]
Have 2 warnings:

`Warning:(396, 39) assigning to 'id<CAAnimationDelegate> _Nullable' from incompatible type 'BFPaperTableViewCell *const __strong'`

It seems that BFPaperTableViewCell () is missing conform to CAAnimationDelegate, so it might be pretty straightforward fix.

PS: in BFPaperCheckbox it seems to be already fixed

**Comment by bfeher** [comment]
Hi @Emailrus!

Thanks for using BFPaperTableViewCell and for bringing this to my attention.
As you noticed in BFPaperCheckbox, this issue (introduced in iOS10 with the addition of CAAnimationDelegate) has been fixed by adding this line in '.h':

```objective-c
#if __IPHONE_OS_VERSION_MAX_ALLOWED < 100000
// CAAnimationDelegate is not available before iOS 10 SDK
@interface BFPaperCheckbox : UIControl <UIGestureRecognizerDelegate>
#else
@interface BFPaperCheckbox : UIControl <UIGestureRecognizerDelegate,CAAnimationDelegate>
#endif
```

I'm out of the office today at an expo, but when I return I will update this project with the same check. Thanks!

**Comment by bfeher** [comment]
Version 2.3.10 has this fix. Please update and let me know if you find anymore problems. 
Thanks again!

**Comment by Emailrus** [comment]
No problems, thank you very much
